import { connectDb, disconnectDb } from "../db.js";
import { Tip } from "../models/Tip.js";
import { SLIP_PRODUCTS } from "../products.js";
import { addDays, startOfDay } from "../utils/dates.js";

function atHour(dayOffset: number, hour: number, minute = 0): Date {
  const d = startOfDay(addDays(new Date(), dayOffset));
  d.setHours(hour, minute, 0, 0);
  return d;
}

const boardOdds = [
  {
    kickoffAt: atHour(-1, 15, 0),
    league: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Brentford",
    prediction: "Home",
    odds: 1.55,
    status: "won" as const,
    product: "odds10",
    bookingCode: "10ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 15, 0),
    league: "Premier League",
    homeTeam: "Chelsea",
    awayTeam: "Fulham",
    prediction: "Over 1.5",
    odds: 1.4,
    status: "won" as const,
    product: "odds10",
    bookingCode: "10ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 17, 30),
    league: "La Liga",
    homeTeam: "Real Sociedad",
    awayTeam: "Getafe",
    prediction: "Home",
    odds: 1.72,
    status: "won" as const,
    product: "odds10",
    bookingCode: "10ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 20, 0),
    league: "Serie A",
    homeTeam: "Inter",
    awayTeam: "Monza",
    prediction: "Over 1.5",
    odds: 1.38,
    status: "lost" as const,
    product: "odds10",
    bookingCode: "10ODDS-YEST",
  },
  {
    kickoffAt: atHour(0, 14, 30),
    league: "Premier League",
    homeTeam: "Liverpool",
    awayTeam: "Everton",
    prediction: "Home",
    odds: 1.48,
    status: "pending" as const,
    product: "odds10",
    bookingCode: "10ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 15, 0),
    league: "Premier League",
    homeTeam: "Man City",
    awayTeam: "Wolves",
    prediction: "Over 1.5",
    odds: 1.3,
    status: "pending" as const,
    product: "odds10",
    bookingCode: "10ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 16, 0),
    league: "Ligue 1",
    homeTeam: "PSG",
    awayTeam: "Nantes",
    prediction: "Home",
    odds: 1.22,
    status: "pending" as const,
    product: "odds10",
    bookingCode: "10ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 17, 30),
    league: "Bundesliga",
    homeTeam: "Bayern",
    awayTeam: "Augsburg",
    prediction: "Over 1.5",
    odds: 1.28,
    status: "pending" as const,
    product: "odds10",
    bookingCode: "10ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 19, 0),
    league: "Eredivisie",
    homeTeam: "PSV",
    awayTeam: "Sparta",
    prediction: "Home",
    odds: 1.35,
    status: "pending" as const,
    product: "odds10",
    bookingCode: "10ODDS-TODAY",
  },

  {
    kickoffAt: atHour(-1, 16, 0),
    league: "Championship",
    homeTeam: "Leeds",
    awayTeam: "Middlesbrough",
    prediction: "Home",
    odds: 1.85,
    status: "won" as const,
    product: "odds50",
    bookingCode: "50ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 18, 0),
    league: "La Liga",
    homeTeam: "Atletico",
    awayTeam: "Villarreal",
    prediction: "BTTS",
    odds: 1.78,
    status: "won" as const,
    product: "odds50",
    bookingCode: "50ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 20, 0),
    league: "Serie A",
    homeTeam: "Atalanta",
    awayTeam: "Roma",
    prediction: "Over 2.5",
    odds: 1.9,
    status: "lost" as const,
    product: "odds50",
    bookingCode: "50ODDS-YEST",
  },
  {
    kickoffAt: atHour(0, 15, 0),
    league: "Premier League",
    homeTeam: "Newcastle",
    awayTeam: "West Ham",
    prediction: "Home",
    odds: 1.7,
    status: "pending" as const,
    product: "odds50",
    bookingCode: "50ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 16, 30),
    league: "La Liga",
    homeTeam: "Barcelona",
    awayTeam: "Celta",
    prediction: "Over 2.5",
    odds: 1.62,
    status: "pending" as const,
    product: "odds50",
    bookingCode: "50ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 17, 45),
    league: "Serie A",
    homeTeam: "Milan",
    awayTeam: "Torino",
    prediction: "Home or Over 1.5",
    odds: 1.55,
    status: "pending" as const,
    product: "odds50",
    bookingCode: "50ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 19, 0),
    league: "Ligue 1",
    homeTeam: "Marseille",
    awayTeam: "Nice",
    prediction: "BTTS",
    odds: 1.72,
    status: "pending" as const,
    product: "odds50",
    bookingCode: "50ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 20, 0),
    league: "Bundesliga",
    homeTeam: "Dortmund",
    awayTeam: "Freiburg",
    prediction: "Over 2.5",
    odds: 1.68,
    status: "pending" as const,
    product: "odds50",
    bookingCode: "50ODDS-TODAY",
  },

  {
    kickoffAt: atHour(-1, 17, 0),
    league: "Europa League",
    homeTeam: "Porto",
    awayTeam: "Lazio",
    prediction: "Home",
    odds: 2.05,
    status: "won" as const,
    product: "odds100",
    bookingCode: "100ODDS-YEST",
  },
  {
    kickoffAt: atHour(-1, 19, 45),
    league: "Champions League",
    homeTeam: "Sporting",
    awayTeam: "Club Brugge",
    prediction: "Over 2.5",
    odds: 1.95,
    status: "lost" as const,
    product: "odds100",
    bookingCode: "100ODDS-YEST",
  },
  {
    kickoffAt: atHour(0, 15, 0),
    league: "Premier League",
    homeTeam: "Aston Villa",
    awayTeam: "Brighton",
    prediction: "Home or BTTS",
    odds: 1.8,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 16, 0),
    league: "La Liga",
    homeTeam: "Real Madrid",
    awayTeam: "Betis",
    prediction: "Home",
    odds: 1.45,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 17, 0),
    league: "Serie A",
    homeTeam: "Napoli",
    awayTeam: "Fiorentina",
    prediction: "Over 2.5",
    odds: 1.88,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 18, 30),
    league: "Ligue 1",
    homeTeam: "Lyon",
    awayTeam: "Monaco",
    prediction: "BTTS",
    odds: 1.7,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 19, 45),
    league: "Bundesliga",
    homeTeam: "Leipzig",
    awayTeam: "Stuttgart",
    prediction: "Over 2.5",
    odds: 1.75,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },
  {
    kickoffAt: atHour(0, 20, 0),
    league: "Champions League",
    homeTeam: "Benfica",
    awayTeam: "Ajax",
    prediction: "Home or Over 1.5",
    odds: 1.6,
    status: "pending" as const,
    product: "odds100",
    bookingCode: "100ODDS-TODAY",
  },

  {
    kickoffAt: atHour(-1, 16, 0),
    league: "La Liga",
    homeTeam: "Sevilla",
    awayTeam: "Valencia",
    prediction: "Draw",
    odds: 3.2,
    status: "lost" as const,
    product: "draw",
    bookingCode: "DRAW-YEST",
  },
  {
    kickoffAt: atHour(-1, 19, 0),
    league: "Serie A",
    homeTeam: "Bologna",
    awayTeam: "Udinese",
    prediction: "Draw",
    odds: 3.1,
    status: "won" as const,
    product: "draw",
    bookingCode: "DRAW-YEST",
  },
  {
    kickoffAt: atHour(0, 15, 0),
    league: "Premier League",
    homeTeam: "Crystal Palace",
    awayTeam: "Brentford",
    prediction: "Draw",
    odds: 3.25,
    status: "pending" as const,
    product: "draw",
    bookingCode: "DRAW-TODAY",
  },
  {
    kickoffAt: atHour(0, 17, 0),
    league: "La Liga",
    homeTeam: "Osasuna",
    awayTeam: "Mallorca",
    prediction: "Draw",
    odds: 3.05,
    status: "pending" as const,
    product: "draw",
    bookingCode: "DRAW-TODAY",
  },
  {
    kickoffAt: atHour(0, 19, 30),
    league: "Serie A",
    homeTeam: "Juventus",
    awayTeam: "Roma",
    prediction: "Draw",
    odds: 3.4,
    status: "pending" as const,
    product: "draw",
    bookingCode: "DRAW-TODAY",
  },

  {
    kickoffAt: atHour(-1, 18, 0),
    league: "Premier League",
    homeTeam: "Tottenham",
    awayTeam: "Bournemouth",
    prediction: "2-1",
    odds: 8.5,
    status: "won" as const,
    product: "correctScore",
    bookingCode: "CS-YEST",
  },
  {
    kickoffAt: atHour(0, 15, 0),
    league: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Nottm Forest",
    prediction: "2-0",
    odds: 7.5,
    status: "pending" as const,
    product: "correctScore",
    bookingCode: "CS-TODAY",
  },
  {
    kickoffAt: atHour(0, 17, 30),
    league: "La Liga",
    homeTeam: "Atletico",
    awayTeam: "Girona",
    prediction: "1-0",
    odds: 6.5,
    status: "pending" as const,
    product: "correctScore",
    bookingCode: "CS-TODAY",
  },
  {
    kickoffAt: atHour(0, 20, 0),
    league: "Champions League",
    homeTeam: "Man City",
    awayTeam: "Inter",
    prediction: "2-1",
    odds: 9.0,
    status: "pending" as const,
    product: "correctScore",
    bookingCode: "CS-TODAY",
  },
].map((tip) => ({ ...tip, isVip: true }));

export async function seedOdds(): Promise<void> {
  await Tip.deleteMany({});
  await Tip.insertMany(boardOdds);

  const counts = await Tip.aggregate<{ _id: string; count: number }>([
    { $group: { _id: "$product", count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]);

  console.log(`Inserted ${boardOdds.length} games into oddnext`);
  for (const board of SLIP_PRODUCTS) {
    const row = counts.find((item) => item._id === board.id);
    console.log(
      `${board.label} · GHS ${board.priceGhs}: ${row?.count ?? 0} games`
    );
  }
}

const isDirectRun = process.argv[1]?.includes("seedOdds");
if (isDirectRun) {
  connectDb()
    .then(() => seedOdds())
    .then(() => disconnectDb())
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
